
# Settings
baseurl = "http://example.org/"
languageCode = "en-us"
title = "GONCALOS LITTLE MY LITTLE PONY CORNER"
theme = "autophugo"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[Author]
    name = "Mestre das 14"
    email = "hugos.18@hotmail.com"

[params]
    # Meta
    description = "Goncalos little corner"
    keywords = "my little ponies"
    #msvalidate = ""
    #googlesiteverification = ""
    #thumb_width = 480
    #thumb_quality = 50
    #full_width = 960
    #full_quality = 90
    
    # Headerbar links
    # Do not put here too many links,
    # it will break mobile appearance

    [[params.header.links]]
    name = "About"
    url = "#footer"
    icon = "fa-info-circle"    
    
    # Footer panel
    
    [params.footer.paragraph]
    headline = "Love My Little Pony"
    text = "YESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"
    
    [params.footer.social]
    headline = "Follow me"

    [[params.footer.social.links]]
    label = "Twitter"
    url = "https://twitter.com/gugateixeira99"
    icon = "fa-twitter"

    [[params.footer.social.links]]
    label = "Facebook"
    url = "https://www.facebook.com/goncaloteixeira99"
    icon = "fa-facebook"

    [[params.footer.social.links]]
    label = "Instagram"
    url = "https://www.instagram.com/goncalo_teixeira99/"
    icon = "fa-instagram"

    [[params.footer.social.links]]
    label = "LinkedIn"
    url = "https://www.linkedin.com/in/goncalo-teixeira99/"
    icon = "fa-linkedin"
    
    
    [params.footer.contact]
    hide = false # Set this to true if you don't want to have a contact form on your site
    realEmail = "hugos.18@hotmail.com"
    headline = "Get in touch for more pics of Goncalo"
    buttonText = "Send"
    resetText = "Reset"
    
    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Name *"
    warning = "Please, enter your name"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Please, enter your email."

    [params.footer.contact.message]
    text = "Message *"
    warning = "Please, enter your message"
    
    # Copyright
    [params.footer.copyright]
    name = "BIGGG BOYYYYYYYYYYY"
